# Generated by Django 4.2.30 on 2026-05-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_volunteerprofile_ngoprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='ngo',
            name='ngo_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='NGOProfile',
        ),
        migrations.DeleteModel(
            name='VolunteerProfile',
        ),
    ]
