# Generated by Django 4.2.30 on 2026-05-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_remove_volunteerprofile_user_ngo_ngo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='ngo_id',
            field=models.CharField(default='temp', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteer_id',
            field=models.CharField(default='temp', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
